miniconda_ver: '4.5.12'
miniconda_checksums:
  Miniconda3-4.5.12-Linux-x86_64.sh: md5:866ae9dff53ad0874e1d1a60b1ad1ef8
miniconda_make_sys_default: true

conda_env_name: jnote
conda_env_environment: conda-jnote.yml
conda_env_activate_for_login_shell: true
