- hosts: all
  pre_tasks:
  - name: Verify Ansible version requirements.
    assert:
      that: "ansible_version.full is version_compare('2.8', '>=')"
  remote_user: vagrant
  vars:
    jupyter_notebook_storage_repo: git@github.com:sawatani/jupyter_storage.git
    jupyter_kernels:
    - haskell
    - maxima
    - rstudio
    github_account:
      name: 沢谷 邦夫
      email: fsawa@fathens.org
  roles:
  - account
  - spacemacs
  - sawatani.jupyter_kernels
