- hosts: targets
  remote_user: vagrant
  roles:
  - role: manala.apt
    become: yes
  - account
  - ssh-config
  - andrewrothstein.miniconda
  - andrewrothstein.conda-env
  - ansible-haskell
  - ihaskell
  - jupyter-notebook
  - spacemacs
