- name: Set timezone
  become: yes
  command: timedatectl set-timezone Asia/Tokyo

- name: bashrc
  blockinfile:
    dest: "{{ansible_env.HOME}}/.bashrc"
    create: yes
    block: |
      {{bashrc_contents}}

- name: gitconfig
  blockinfile:
    dest: "{{ansible_env.HOME}}/.gitconfig"
    create: yes
    block: |
      {{gitconfig_contents}}
