- name: get jupyter data dir
  command: bash -l -c 'jupyter --data-dir'
  register: jupyter_data_dir
- name: clone jupyter-vim-binding
  git:
    repo: "{{jupyter_vim_binding_repo}}"
    dest: "{{jupyter_data_dir.stdout}}/nbextensions/vim_binding"

- name: enable jupyter extentions
  command: "bash -l -c 'jupyter nbextension enable {{item}}'"
  with_items: "{{jupyter_extentions}}"

- name: clone storage of jupyter notebooks
  git:
    repo: "{{jupyter_notebook_storage.repo}}"
    dest: "{{jupyter_notebook_storage.dir}}"
    update: no
    force: no
- name: setup git config to clean ipynb
  blockinfile:
    path: "{{jupyter_notebook_storage.dir}}/.git/{{item.file}}"
    create: yes
    block: |
      {{item.content}}
  with_items:
  - "{{jupyter_notebook_gitconfig}}"

- name: put jupyter's run.sh
  with_items:
    - f: jupyter-run.sh
      d: "{{jupyter_notebook_dir}}/run.sh"
      m: '0744'
    - f: jupyter-config.py
      d: "{{jupyter_notebook_dir}}/config.py"
  template:
    src: "{{item.f}}.j2"
    dest: "{{item.d}}"
    mode: "{{item.m|default('0644')}}"
- name: put jupyter.service
  become: yes
  with_items:
    - f: jupyter.service
      d: /etc/systemd/system
  template:
    src: "{{item.f}}.j2"
    dest: "{{item.d}}/{{item.f}}"
    mode: "{{item.m|default('0644')}}"
- name: start service of jupyter
  become: yes
  shell: |
    systemctl enable jupyter.service
    systemctl daemon-reload
    systemctl restart jupyter.service
