- name: clone HaskellR
  git:
    repo: "{{haskellr.repo}}"
    dest: "{{haskellr.dir}}"
    version: "{{haskellr.version}}"
    force: yes

- name: install HaskellR
  command: bash -l -c 'stack install'
  args:
    chdir: "{{haskellr.dir}}"
    creates: "{{ansible_env.HOME}}/.local/bin/H"

- name: install R libraries
  become: yes
  command: bash -l -c "Rscript -e 'install.packages(\"tidyverse\")'"

- name: install IHaskell to Jupyter
  command: bash -l -c 'stack exec ihaskell install'
  args:
    chdir: "{{haskellr.dir}}"
    creates: "{{ansible_env.HOME}}/.ihaskell"

- name: create alias command of Jupyter HaskellR
  blockinfile:
    dest: "{{ansible_env.HOME}}/.bashrc"
    create: yes
    block: |
      alias jupyter-notebook='(cd {{haskellr.dir}}; stack exec jupyter -- notebook)'
