- name: gitconfig
  become: yes
  blockinfile:
    dest: "{{home_dir}}/.gitconfig"
    mode: "{{item.mode|default('0664')}}"
    owner: "{{username}}"
    group: "{{groupname}}"
    create: yes
    block: |
      {{gitconfig_contents}}

- name: create dir .ssh
  become: yes
  file:
    path: "{{home_dir}}/.ssh"
    state: directory
    mode: "{{item.mode|default('0700')}}"
    owner: "{{username}}"
    group: "{{groupname}}"

- name: copy files of ssh
  become: yes
  copy:
    src: "~/.ssh/{{item.name}}"
    dest: "{{home_dir}}/.ssh/{{item.name}}"
    mode: "{{item.mode|default('0600')}}"
    owner: "{{username}}"
    group: "{{groupname}}"
  with_items:
  - "{{ssh_copy_files}}"

- name: put files of ssh
  become: yes
  blockinfile:
    path: "{{home_dir}}/.ssh/{{item.name}}"
    mode: "{{item.mode|default('0664')}}"
    owner: "{{username}}"
    group: "{{groupname}}"
    create: yes
    block: |
      {{item.content}}
  with_items:
  - "{{ssh_put_files}}"
